services:
  backend:
    build:
      context: ./BackendAPI
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=mydb
  
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


  httpd:
    build:
      context: ./HttpServer
      dockerfile: Dockerfile
    ports:
      - "666:80"
    networks:
      - front-tier
      - app-network
    depends_on:
      - backend

volumes:
  postgres-data:
    driver: local

networks:
  front-tier: {}
  back-tier: {}
  app-network: {}