name: Continuous Deployment

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Stop and remove old containers
          docker stop backend database httpd || true
          docker rm backend database httpd || true

          # Pull latest images
          docker pull lem0hn/tp-devops-database:latest
          docker pull lem0hn/tp-devops-simple-api:latest
          docker pull lem0hn/tp-devops-httpd:latest

          # Start database
          docker run -d \
            --name database \
            --network app-network \
            -e POSTGRES_USER=usr \
            -e POSTGRES_PASSWORD=pwd \
            -e POSTGRES_DB=db \
            -v /home/admin/CreateScheme.sql:/docker-entrypoint-initdb.d/01-CreateScheme.sql \
            -v /home/admin/InsertData.sql:/docker-entrypoint-initdb.d/02-InsertData.sql \
            -p 5432:5432 \
            lem0hn/tp-devops-database:latest

          # Start backend
          docker run -d \
            --name backend \
            --network app-network \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db \
            -e SPRING_DATASOURCE_USERNAME=usr \
            -e SPRING_DATASOURCE_PASSWORD=pwd \
            -p 8080:8080 \
            lem0hn/tp-devops-simple-api:latest

          # Start proxy
          docker run -d \
            --name httpd \
            --network app-network \
            -p 80:80 \
            lem0hn/tp-devops-httpd:latest
