name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
    - main
    - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
    #checkout your github code using actions/checkout@v4
    - uses: actions/checkout@v4

    #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    #finally build your app with the latest command
    - name: Build and test with Maven
      run: mvn -f TP02/BackendAPI/pom.xml clean verify

    - name: SonarCloud
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Lem0n10_Lem0n10-Docker-CTP -Dsonar.organization=lem0n10 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./TP02/BackendAPI/pom.xml
  # define job to build and publish docker image


  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./TP02/BackendAPI
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./TP02/Database
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest

        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        # relative path to the place where source code with Dockerfile is located
        context: ./TP02/HttpServer
        # Note: tags has to be all lower-case
        tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest

        # build on feature branches, push only on main branch   
        push: ${{ github.ref == 'refs/heads/main' }}

  deploy-to-server:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible

    - name: Deploy with Ansible
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        ansible-playbook -i TP02/Ansible/inventories/setup.yml TP02/Ansible/playbook.yml \
          -e "db_user=$DB_USER db_password=$DB_PASSWORD dockerhub_user=$DOCKERHUB_USERNAME" \
          --private-key "${{ secrets.SERVER_SSH_KEY }}" \
          -u ${{ secrets.SERVER_USER }} \
          -e "ansible_host=${{ secrets.SERVER_HOST }}"
